// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyiyz5L6KY7vGTrbuWe55r0_qnC1_jFg',
    appId: '1:149531310041:web:a0573580b0b9f42c974bc8',
    messagingSenderId: '149531310041',
    projectId: 'fasum-app-8b00d',
    authDomain: 'fasum-app-8b00d.firebaseapp.com',
    storageBucket: 'fasum-app-8b00d.firebasestorage.app',
    measurementId: 'G-BHTDBQVB38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSCUJYnvEqVGtrYk8AX_mJ1YlTCk0Q2o',
    appId: '1:149531310041:android:d04e4227738320f8974bc8',
    messagingSenderId: '149531310041',
    projectId: 'fasum-app-8b00d',
    storageBucket: 'fasum-app-8b00d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOhN1pUPlNpY7yx6FZjKKl4NHULhO298',
    appId: '1:149531310041:ios:fc2c227e8bddebb8974bc8',
    messagingSenderId: '149531310041',
    projectId: 'fasum-app-8b00d',
    storageBucket: 'fasum-app-8b00d.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOhN1pUPlNpY7yx6FZjKKl4NHULhO298',
    appId: '1:149531310041:ios:fc2c227e8bddebb8974bc8',
    messagingSenderId: '149531310041',
    projectId: 'fasum-app-8b00d',
    storageBucket: 'fasum-app-8b00d.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAyiyz5L6KY7vGTrbuWe55r0_qnC1_jFg',
    appId: '1:149531310041:web:b652951f18d480d9974bc8',
    messagingSenderId: '149531310041',
    projectId: 'fasum-app-8b00d',
    authDomain: 'fasum-app-8b00d.firebaseapp.com',
    storageBucket: 'fasum-app-8b00d.firebasestorage.app',
    measurementId: 'G-SV8MB3C6WZ',
  );
}
